[build]
  command = "npm run build" # the command you run to build this file
  functions = "built-lambda" # netlify-lambda builds to this folder AND Netlify reads functions from here
  environment = { mongoURI = "mongodb://myiu:mikeyiu1@ds143573.mlab.com:43573/devshub", secret = "secret"}